language: python
pyhton:
    -3.7
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - cd books/ && ./manage.py test
  - cd readers/ && ./manage.py test
  - cd authors/ && ./manage.py test
