# Generated by Django 2.2.5 on 2020-01-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=200),
        ),
    ]
