# Generated by Django 2.2.5 on 2019-10-20 20:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('readers_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='id',
        ),
        migrations.AddField(
            model_name='reader',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
